### ISSUE TITLE
13.11 Goal 3 - Enlarge list of cities from which data is collected

### ISSUE THREAD

**Issue by phinik** [phinik/LovelyLLamas#10]
1. We should aim at ~1000 cities.
2. Pay attention to the spelling of the city names. They must be spelled exactly how wetter.com spells them in the weather reports.

**Comment by Ace-Of-Snakes** [comment]
This has been done by my commits, which have added 113 000 cities to our city database by crawling through the wetter.com website. 
More so through this link https://www.wetter.com/deutschland/EUDE.html where you can select a continent, country, regions and cities from their database. The links to the other websites are in the option-html-tags.
When you go to the website for Africa for example, you can see all possible countries in the option-tags, after that you select the link to a specific country and so on.
This took around 8 hours of crawling time alone due to O(n^4) complexity

**Comment by Ace-Of-Snakes** [comment]
P.S. -> due to crawling wetter.com the names automatically match
